apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-svc
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: {{ .Values.namespace }}
    version: {{ .Values.image.tag }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
